<?php

/* LabVIEW interface implementation. */
$this->headScript()->appendFile($this->baseUrl('/js/ModelRig/Model.js'));
$this->headLink()->appendStylesheet($this->baseUrl('/css/ModelRig/Model.css'));

/* Canvas compatability implementation for Internet Explorer 8 and earlier. */
$this->headScript()->appendFile($this->baseUrl('js/excanvas.js'),
        'text/javascript',
        array('conditional' => 'lt IE 9')
);

/* Touch events punching to mouse events. */
//$this->headScript()->appendFile($this->baseUrl('uts/coupledtanksnew/jquery.ui.touch-punch.js'));
?>

<div id="coupled-tanks-anchor">
    <!-- Interface goes here! -->
</div>


<script type="text/javascript">
$(document).ready(function() {
	var inter = new LabVIEWControl("coupled-tanks-anchor");
	inter.setup();
	inter.run();
});
</script>
